csgo:
  image: chpio/csgo-server
  restart: on-failure
  ports:
    - "27015:27015/udp"
  command: >
    -game csgo
    -console
    -usercon
    +game_type 0
    +game_mode 0
    +mapgroup mg_active
    +map de_dust2
